### ISSUE TITLE
resizeService not injected in test environment

### ISSUE THREAD

**Issue by timiyay** [mike-north/ember-resize#43]
**Versions**
ember 2.4.4
ember-resize 0.0.12

**Problem**
I recently integrated `ember-resize` into a component, which broke my integration tests. The component rendered and behaved as expected during development, but test runs would fail.

Even though I stubbed the `resizeService` as per the [Ember component testing docs](https://guides.emberjs.com/v2.5.0/testing/testing-components/#toc_stubbing-services), the tests failed due to `resizeService` being `undefined`.

It appears that `ember-resize` does not inject the service in the test environment.

Example Test:

``` js
// tests/integration/components/my-component-test.js

const resizeServiceStub = Ember.Service.extend({
  on() {}
});

test('it renders', function(assert) {
    this.register('service:resize', resizeServiceStub);
    this.inject.service('resize', { as: 'resizeService' });

    this.render(hbs`{{my-component}}`);
});

// TEST FAILED: TypeError: Cannot read property 'on' of undefined
```

**Workaround**

The problem can be fixed by manually-injecting the service into your component, in your app code

``` js
// app/components/my-component.js

resizeService: Ember.inject.service('resize')
```

This injection is redundant outside of the test environment, but required within it.

**Comment by mike-north** [comment]
I think the solution here is to clarify in the README what needs to be done. I'm wary about injecting services into unit tests without the developer being explicit about it

**Comment by timiyay** [comment]
In this case, we're talking about integration tests, rather than unit tests. 

For mine, the expected behaviour for component integration tests is that service injection mirrors development/prod. If a service is injected in development/prod, it's injected in test. This matches the behaviour of other service-injecting Ember add-ons.

In my case, I had to change my production code to enable test-specific behaviour. I'm already being explicit about the fact I need the `resizeService`, as per the Ember testing docs. 

The bug is that, even after I register the service with
```js
this.register('service:resize', resizeServiceStub);
this.inject.service('resize', { as: 'resizeService' });
```

...it's still not available in my tests.

**Comment by Fryie** [comment]
I could be wrong, but afaik you should always inject services even in your production code. That is, `resizeService: Ember.inject.service('resize')` is exactly the way you should do it.

**Comment by localpcguy** [comment]
My expectation (and I could have the wrong expectation) is that if I don't need to inject the service in my component in order for it to work, and integration test should not then require me to inject it. You end up in a state where your code works, but the tests fail. While updating the documentation could make this easier to debug when a dev comes across it, personally, I think it would be better to either 

1. work without the service being injected by the developer just to make the test work
2. require the service to be injected by the developer in order to use the mixin (thereby also working in the test)

**Comment by myartsev** [comment]
It's been a while since the last update, just wanted to throw out a +1 that this is an issue.

For now I'm going to (redundantly) inject the service into production code.
My intuition is that this should be the default behaviour, ember-resize should not automatically inject itself into every component. I'm fairly new to Ember, but there is something off here; changing production code to enable test specific behaviour.

**Comment by chriskrycho** [comment]
I've started seeing this with *acceptance* tests after upgrading to Ember 2.13.
